name: Windows

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  msvc2022:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [x64]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            **/build/_deps
          key: ${{ runner.os }}.${{ github.job }}.${{ hashFiles('**/TinyEngine/vendor/CMakeLists.txt') }}
          restore-keys: ${{ runner.os }}.${{ github.job }}.

      - name: Run CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.architecture }} -DBuildTests=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 10

      - name: Google Test
        run: cd build; ctest -j 10 -C ${{ matrix.build_type }}  --output-on-failure
